FROM alpine

RUN apk update && \
    apk add --no-cache python3 py3-pip py3-psycopg2 gcc python3-dev musl-dev postgresql-dev && \
    pip3 install pyTelegrambotAPI --break-system-packages && \
    mkdir /app

COPY telegram_bot.py /app/telegram_bot.py

WORKDIR /app

CMD [ "python3", "telegram_bot.py" ]
